### ISSUE TITLE
Conditional statement problem with OR

### ISSUE THREAD

**Issue by elliottinvent** [MODLanguage/java-interpreter#24]
This returns as expected:
```
_country=gb
{
  country = gb | country = us?
    support_number=+441270123456
  /?
    support_number=+14161234567
}
```
->
```
{
    "support_number": "+441270123456"
}
```

But this doesn't (just switched around tests):
```
_country=gb
{
  country = us | country = gb?
    support_number=+441270123456
  /?
    support_number=+14161234567
}
```
-> `null`

**Comment by twalmsley** [comment]
I added base_tests to the grammar repo for these examples - the second one also fails in the Ruby interpreter and it looks like a grammar problem. 

We get a very different parse tree if the `|` is replaced by `&`, but the two trees should be identical apart from that one character.

When the pipe is used, the second part of the condition, i.e. `country = us?` is parsed as a `modl_pair` rather than a `modl_condition`, which changes the semantics of the condition and only the first part is evaluated correctly.

I have a grammar change that will fix the parsing, but there will be a non-trivial impact on the interpreters. I'll fix the Ruby version first and then move on to the Java and JS version.

The problem is caused by the use of `modl_value` here:
```
modl_condition
  // e.g. country=gb
  : NEWLINE* STRING? modl_operator? modl_value (PIPE modl_value )* NEWLINE*
  ;
```
And the fix changes this to :
```
modl_condition
  // e.g. country=gb
  : NEWLINE* STRING? modl_operator? modl_primitive (PIPE modl_primitive )* NEWLINE*
  ;
```
Which also requires:
```
modl_primitive
  : QUOTED
  | NUMBER
  | STRING
  | TRUE
  | FALSE
  | NULL
;
```
I _could_ also use `modl_primitive` to replace these values in `modl_value` and `modl_array_value_item`, like this (but there will be a bigger impact on the interpreters), what do you think?:
```
modl_value
  : modl_map
  | modl_array
  | modl_nb_array
  | modl_pair
  | modl_primitive
;

modl_array_value_item
  : modl_map
  | modl_pair
  | modl_array
  | modl_primitive
;
```
Let me know if you spot any problems with the proposed grammar change.

**Comment by twalmsley** [comment]
Its probably also worth changing `STRING?` to `modl_primitive?` in:
```
modl_condition
  // e.g. country=gb
  : NEWLINE* STRING? modl_operator? modl_value (PIPE modl_value )* NEWLINE*
  ;
```
to give
```
modl_condition
  // e.g. country=gb
  : NEWLINE* modl_primitive? modl_operator? modl_value (PIPE modl_value )* NEWLINE*
  ;
```

**Comment by twalmsley** [comment]
The Ruby interpreter now works with this change for all tests - the changes for both the grammar and the Ruby interpreter are on branches called `grammar_pipe_issue` and I'll hold off merging them to master until @elliottinvent has had a chance to comment on the grammar change, and/or run some additional tests against the changes in the `grammar_pipe_issue` branch.

**Comment by twalmsley** [comment]
Fixed.
